{{- $namespaces := dict "_0" .Release.Namespace -}}
{{- if and .Values.grafana.enabled .Values.grafana.defaultDashboardsEnabled (not .Values.grafana.defaultDashboards.useExistingNamespace) -}}
{{- $_ := set $namespaces "_1" .Values.grafana.defaultDashboards.namespace -}}
{{- end -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Chart.Name }}-patch-sa
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}-patch-sa
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded, before-hook-creation
spec:
  template:
    metadata:
      name: {{ .Chart.Name }}-patch-sa
      labels:
        app: {{ .Chart.Name }}-patch-sa
    spec:
      serviceAccountName: {{ .Chart.Name }}-patch-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      restartPolicy: Never
      nodeSelector: {{ include "linux-node-selector" . | nindent 8 }}
      tolerations: {{ include "linux-node-tolerations" . | nindent 8 }}
      containers:
      {{- range $_, $ns := $namespaces }}
        - name: patch-sa-{{ $ns }}
          image: {{ template "system_default_registry" $ }}{{ $.Values.global.kubectl.repository }}:{{ $.Values.global.kubectl.tag }}
          imagePullPolicy: {{ $.Values.global.kubectl.pullPolicy }}
          command: ["kubectl", "patch", "serviceaccount", "default", "-p", "{\"automountServiceAccountToken\": false}"]
          args: ["-n", "{{ $ns }}"]
{{- if $.Values.global.kubectl.resources }}
          resources: {{ toYaml $.Values.global.kubectl.resources | nindent 10 }}
{{- end }}
{{- if $.Values.global.kubectl.containerSecurityContext }}
          securityContext: {{ toYaml $.Values.global.kubectl.containerSecurityContext | nindent 10 }}
{{- end }}
      {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Chart.Name }}-patch-sa
  labels:
    app: {{ .Chart.Name }}-patch-sa
rules:
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs: ['get', 'patch']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Chart.Name }}-patch-sa
  labels:
    app: {{ .Chart.Name }}-patch-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Chart.Name }}-patch-sa
subjects:
  - kind: ServiceAccount
    name: {{ .Chart.Name }}-patch-sa
    namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}-patch-sa
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}-patch-sa
{{- if .Values.hardened.k3s.networkPolicy.enabled }}
{{- range $_, $ns := $namespaces }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: project-monitoring-policy
  namespace: {{ $ns }}
spec:
  podSelector: {}
  ingress: {{- default (list dict | toYaml) (include "kube-prometheus-stack.hardened.networkPolicy.ingress" (list $ $ns)) | nindent 4 }}
  egress: {{- $.Values.global.networkPolicy.egress | toYaml | nindent 4 }}
  policyTypes:
    - Ingress
    - Egress
{{- end }}
{{- end }}