{{- if and .Values.helmProjectOperator.global.rbac.create .Values.helmProjectOperator.global.rbac.userRoles.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "prometheus-federator.name" . }}-admin
  labels: {{ include "prometheus-federator.labels" . | indent 4 }}
  {{- if .Values.helmProjectOperator.global.rbac.userRoles.aggregateToDefaultRoles }}
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
  {{- end }}
rules:
- apiGroups:
  - helm.cattle.io
  resources:
  - projecthelmcharts
  - projecthelmcharts/finalizers
  - projecthelmcharts/status
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "prometheus-federator.name" . }}-edit
  labels: {{ include "prometheus-federator.labels" . | indent 4 }}
  {{- if .Values.helmProjectOperator.global.rbac.userRoles.aggregateToDefaultRoles }}
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  {{- end }}
rules:
- apiGroups:
  - helm.cattle.io
  resources:
  - projecthelmcharts
  - projecthelmcharts/status
  verbs:
  - 'get'
  - 'list'
  - 'watch'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "prometheus-federator.name" . }}-view
  labels: {{ include "prometheus-federator.labels" . | indent 4 }}
  {{- if .Values.helmProjectOperator.global.rbac.userRoles.aggregateToDefaultRoles }}
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  {{- end }}
rules:
- apiGroups:
  - helm.cattle.io
  resources:
  - projecthelmcharts
  - projecthelmcharts/status
  verbs:
  - 'get'
  - 'list'
  - 'watch'
{{- end }}
