apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "prometheus-federator.name" . }}
  labels: {{ include "prometheus-federator.labels" . | indent 4 }}
    app: {{ template "prometheus-federator.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "cluster-admin" # see note below
subjects:
- kind: ServiceAccount
  name: {{ template "prometheus-federator.name" . }}
  namespace: {{ template "prometheus-federator.namespace" . }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "prometheus-federator.name" . }}
  namespace: {{ template "prometheus-federator.namespace" . }}
  labels: {{ include "prometheus-federator.labels" . | indent 4 }}
    app: {{ template "prometheus-federator.name" . }}
{{- if .Values.helmProjectOperator.global.imagePullSecrets }}
imagePullSecrets: {{ toYaml .Values.helmProjectOperator.global.imagePullSecrets | nindent 2 }}
{{- end }}
# ---
# NOTE:
# As of now, due to the fact that the k3s-io/helm-controller can only deploy jobs that are cluster-bound to the cluster-admin
# ClusterRole, the only way for this operator to be able to perform that binding is if it is also bound to the cluster-admin ClusterRole.
#
# As a result, this ClusterRoleBinding will be left as a work-in-progress until changes are made in k3s-io/helm-controller to allow us to grant
# only scoped down permissions to the Job that is deployed.
