#!/bin/bash
set -e
set -x

E2E_SCRIPTS_ROOT=$(realpath $(dirname $0))
GIT_ROOT=$(realpath "$E2E_SCRIPTS_ROOT/../../../..")

cd $GIT_ROOT
source "$GIT_ROOT/scripts/version"

DEFAULT_SLEEP_TIMEOUT_SECONDS=${DEFAULT_SLEEP_TIMEOUT_SECONDS:-10}
KUBECTL_WAIT_TIMEOUT=${KUBECTL_WAIT_TIMEOUT:-120s}

if [[ ${DEBUG} == "true" ]]; then
    echo "Enabling DEBUG mode..."
    set -x
fi

echo "Using rancher monitoring version : ${RANCHER_MONITORING}"

if [ "$RANCHER_MONITORING" != "latest" ]; then
    RANCHER_MONITORING_VERSION_HELM_ARGS="--version ${RANCHER_MONITORING}"
fi

if [[ "${E2E_CI}" == "true" ]]; then
    KUBERNETES_DISTRIBUTION_TYPE=k3s
fi

if [[ -n ${RANCHER_URL} ]] && [[ -n ${RANCHER_CLUSTER} ]] && [[ -n ${RANCHER_TOKEN} ]]; then
    if [[ -n ${RANCHER_CLUSTER} && ${RANCHER_CLUSTER} != "local" ]]; then 
        API_SERVER_URL=${RANCHER_URL}/k8s/clusters/${RANCHER_CLUSTER}
    else
        API_SERVER_URL=${RANCHER_URL}
    fi 
    API_SERVER_CURL_AUTH_HEADERS="-k -H 'Authorization: Bearer ${RANCHER_TOKEN}'"
    RANCHER_CLUSTER_HELM_ARGS="--set global.cattle.url=${RANCHER_URL} --set global.cattle.clusterId=${RANCHER_CLUSTER}"
else
    kubectl proxy --port=${APISERVER_PORT:-8001} 2>/dev/null &
    API_SERVER_URL=http://localhost:${APISERVER_PORT:-8001}
    sleep 5
fi

RANCHER_HELM_ARGS="${RANCHER_CLUSTER_HELM_ARGS} ${RANCHER_MONITORING_VERSION_HELM_ARGS}"