#!/bin/bash
set -euo pipefail

# Generates PR body for workflow deployment
# Usage: generate-pr-body.sh <target-branch> <helm-version> <k3s-versions> <automation-core-ref> <github-sha> <github-actor>
# Output: Prints PR body to stdout

TARGET_BRANCH="$1"
HELM_VERSION="$2"
K3S_VERSIONS="$3"
AUTOMATION_CORE_REF="$4"
GITHUB_SHA="$5"
GITHUB_ACTOR="$6"

cat <<EOF
**Automated deployment of automation-core workflows**

## Configuration
- **Helm version**: \`${HELM_VERSION}\`
- **K3S versions**: \`${K3S_VERSIONS}\`
- **Automation-core ref**: \`@${AUTOMATION_CORE_REF}\`
- **Target branch**: \`${TARGET_BRANCH}\`

## Changes
This PR updates the GitHub Actions workflows from automation-core templates.

## Source
- Automation-core commit: \`${GITHUB_SHA:0:7}\`
- Deployed by: @${GITHUB_ACTOR}

---
🤖 Generated by automation-core workflow deployment
EOF
