rancherProjectMonitoringVersion: 0.8.1
rancherMonitoringVersion : 109.0.2+up80.9.1-rancher.8
k3sTestingMaxVersion: v1.35.0+k3s3
k3sTestingMinVersion: v1.33.7+k3s3
kuberlrVersion: v7

# Dev use only
# devChartsSource: https://github.com/{Dev}/ob-team-charts
# devChartsBranch: {your branch}
