annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/display-name: Prometheus Federator
  catalog.cattle.io/namespace: cattle-monitoring-system
  catalog.cattle.io/os: linux,windows
  catalog.cattle.io/permits-os: linux,windows
  catalog.cattle.io/provides-gvr: helm.cattle.io.projecthelmchart/v1alpha1
  catalog.cattle.io/release-name: prometheus-federator
apiVersion: v2
appVersion: 9999
description: Prometheus Federator - installs rancher-project-monitoring in project namespaces.
icon: https://raw.githubusercontent.com/rancher/prometheus-federator/main/assets/logos/prometheus-federator.svg
keywords:
  - prometheus
  - monitoring
  - project-monitoring
maintainers:
  - email: alexandre.lamarre@suse.com
    name: Alexandre
  - email: dan.pock@suse.com
    name: Dan
  - email: julia.suriano@suse.com
    name: Julia
name: prometheus-federator
version: 9999
