// Code generated by pkg/codegen/config/main.go. DO NOT EDIT.
// Package buildconfig contains a set of exported constants that represent configuration variables of Rancher at build-time.
package buildconfig

const (
	K3sTestingMaxVersion            = "v1.35.0+k3s3"
	K3sTestingMinVersion            = "v1.33.7+k3s3"
	KuberlrVersion                  = "v7"
	RancherMonitoringVersion        = "109.0.6+up80.9.1-rancher.22"
	RancherProjectMonitoringVersion = "0.8.3"
)
