// Code generated by pkg/codegen/config/main.go. DO NOT EDIT.
// Package buildconfig contains a set of exported constants that represent configuration variables of Rancher at build-time.
package buildconfig

const (
	K3sTestingMaxVersion            = "v1.36.0-k3s1"
	K3sTestingMinVersion            = "v1.34.7+k3s1"
	KuberlrVersion                  = "v8"
	RancherMonitoringVersion        = "109.0.2+up80.9.1-rancher.8"
	RancherProjectMonitoringVersion = "0.8.0"
)
