// Code generated by pkg/codegen/config/main.go. DO NOT EDIT.
// Package buildconfig contains a set of exported constants that represent configuration variables of Rancher at build-time.
package buildconfig

const (
	K3sTestingMaxVersion            = "v1.30.11-k3s1"
	K3sTestingMinVersion            = "v1.27.16-k3s1"
	RancherMonitoringVersion        = "104.1.4+up57.0.3"
	RancherProjectMonitoringVersion = "0.3.4"
)
