apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: helmreleases.helm.cattle.io
spec:
  group: helm.cattle.io
  names:
    kind: HelmRelease
    plural: helmreleases
    singular: helmrelease
  preserveUnknownFields: false
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.release.name
      name: Release Name
      type: string
    - jsonPath: .spec.release.namespace
      name: Release Namespace
      type: string
    - jsonPath: .status.version
      name: Version
      type: string
    - jsonPath: .status.state
      name: State
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              release:
                properties:
                  name:
                    nullable: true
                    type: string
                  namespace:
                    nullable: true
                    type: string
                type: object
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      nullable: true
                      type: string
                    lastUpdateTime:
                      nullable: true
                      type: string
                    message:
                      nullable: true
                      type: string
                    reason:
                      nullable: true
                      type: string
                    status:
                      nullable: true
                      type: string
                    type:
                      nullable: true
                      type: string
                  type: object
                nullable: true
                type: array
              description:
                nullable: true
                type: string
              notes:
                nullable: true
                type: string
              state:
                nullable: true
                type: string
              version:
                type: integer
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
