#!/usr/bin/env bash
set -e

source $(dirname $0)/version
source $(dirname $0)/util-chart

# We don't do this for helm-locker
if [[ "${BUILD_TARGET}" == "helm-locker" ]]; then
  exit
fi

cd $(dirname $0)/..

if [ "$BUILD_TARGET" == "prometheus-federator" ]; then
  DEFAULT_CHART_TARGET="rancher-project-monitoring"
elif [ "$BUILD_TARGET" == "helm-project-operator" ]; then
  DEFAULT_CHART_TARGET="project-operator-example"
fi

CHART=${CHART:-${DEFAULT_CHART_TARGET}}
CHART_VERSION=${EMBEDDED_CHART_VERSION:-$(find ./charts/${CHART} -maxdepth 1 -mindepth 1 -type d | tr - \~ | sort -rV | tr \~ - | head -n1 | cut -d'/' -f4)}

# Prepare and package charts
package-charts "charts/${CHART}/${CHART_VERSION}" ./build/charts

# Prepare chart for embedding location
base64 -i "build/charts/${CHART}-${CHART_VERSION}.tgz" > "cmd/${BUILD_TARGET}/fs/${CHART}.tgz.base64"
rm "build/charts/${CHART}-${CHART_VERSION}.tgz"

echo "Completed ${CHART} (${CHART_VERSION}) build process."