#!/usr/bin/env bash
set -e
set -x

if ! hash ginkgo 2>/dev/null; then
    echo "Ginkgo is not installed"
    exit 1
fi

TEST_FLAGS=${TEST_FLAGS:-""}

COVER=${COVER:-""}
if [ "$COVER" == "true" ]; then
  TEST_FLAGS="$TEST_FLAGS --cover --covermode=atomic --coverprofile=cover.out --coverpkg=github.com/rancher/prometheus-federator/..."
fi

ginkgo -p -tags=integration ${TEST_FLAGS} ./internal/integration/