#!/usr/bin/env bash
set -e
set -x

if ! hash ginkgo 2>/dev/null; then
    echo "Ginkgo is not installed"
    exit 1
fi

if ! hash helm 2>/dev/null; then
    echo "Helm is not installed"
    exit 1
fi

TEST_FLAGS=${TEST_FLAGS:-"--output-interceptor-mode=none"}

FOCUS=${FOCUS:-""}

COVER=${COVER:-""}
if [ "$COVER" == "true" ]; then
  TEST_FLAGS="$TEST_FLAGS --cover --covermode=atomic --coverprofile=cover.out --coverpkg=github.com/rancher/prometheus-federator/..."
fi

if [ "$FOCUS" != "" ]; then
  TEST_FLAGS="$TEST_FLAGS --focus=$FOCUS"
fi

ginkgo -p -v -tags=integration ${TEST_FLAGS} ./internal/integration/