#!/usr/bin/env bash
set -e

source $(dirname $0)/version
DOCKER_TARGET=${DOCKER_TARGET:-"-${BUILD_TARGET}"}

cd $(dirname $0)/..

echo "Starting \`${DOCKER_TARGET}\` image packaging:";

DOCKERFILE=package/Dockerfile${DOCKER_TARGET}
echo "Building \`${IMAGE}\` from \`${DOCKERFILE}\`:";
docker build -f "${DOCKERFILE}" -t "${IMAGE}" .
echo "Completed building ${IMAGE} container image"
