#!/bin/bash
set -e
set -x

if ! hash helm 2>/dev/null; then
    echo "Helm is not installed"
    exit 1
fi

source "$(dirname "$0")/version"
source "$(dirname "$0")/util-chart"
source "$(dirname "$0")/util-team-charts"

# We don't do the full process for prometheus-federator
if [[ "${BUILD_TARGET}" == "prometheus-federator" ]]; then
  # Fetch asset from github OB charts repo
  fetch-team-chart "rancher-project-monitoring" "$RANCHER_PROJECT_MONITORING"
  PROM_FED_CHART=$(newest-chart-version "prometheus-federator")
  fetch-team-chart "prometheus-federator" "$PROM_FED_CHART"
  exit
fi

cd "$(dirname "$0")/.."

if [ "$BUILD_TARGET" == "helm-project-operator" ]; then
  DEFAULT_CHART_SOURCE="./packages/$BUILD_TARGET/charts"
elif [ "$BUILD_TARGET" == "helm-locker" ]; then
  DEFAULT_CHART_SOURCE="./examples/$BUILD_TARGET/helm-locker-chart-example"
fi

clean-old-chart "$BUILD_TARGET"
cp -rf "${DEFAULT_CHART_SOURCE}" "./build/charts/${BUILD_TARGET}"

edit-charts "./build/charts/${BUILD_TARGET}/Chart.yaml" "${HELM_CHART_VERSION}" "${HELM_IMAGE_TAG}"
package-charts "./build/charts/${BUILD_TARGET}"