#!/usr/bin/env bash
set -e

source $(dirname $0)/version
cd $(dirname $0)/..

echo "Starating tests"

TARGET_TEST_TAG="${BUILD_TARGET/-/_}"

echo "Running tests for ${TARGET_TEST_TAG}"
go test -cover -tags="test,${TARGET_TEST_TAG}" ./...
