#!/usr/bin/env bash
set -x


CHARTS_REPO="https://raw.githubusercontent.com/rancher/ob-team-charts"
CHARTS_BRANCH="main"

if grep -v "^#" "$BUILD_YAML_PATH"| grep 'devChartsSource'; then
  TMP_CHARTS_REPO=$(grep -v "^#" "$BUILD_YAML_PATH" | grep 'devChartsSource' |cut -d" " -f2|tr -d ' ')
  CHARTS_REPO=$(echo "$TMP_CHARTS_REPO" | sed 's/github\.com/raw\.githubusercontent\.com/g')
fi
if grep -v "^#" "$BUILD_YAML_PATH"| grep 'devChartsBranch'; then
  CHARTS_BRANCH=$(grep -v "^#" "$BUILD_YAML_PATH" | grep 'devChartsBranch' |cut -d: -f2|tr -d ' ')
fi


function fetch-team-charts-index() {
  TEAM_INDEX="$CHARTS_REPO/refs/heads/$CHARTS_BRANCH/index.yaml"
  BUILD_DIR="./build"
  LOCAL_FILE="$BUILD_DIR/charts-index.yaml"
  LOCAL_ETAG_FILE="$BUILD_DIR/charts-index.etag"

  # Ensure the build directory exists
  mkdir -p "$BUILD_DIR"

  # Fetch the ETag from the remote file headers
  REMOTE_ETAG=$(curl -sI "$TEAM_INDEX" | grep -i "etag" | awk '{print $2}' | tr -d '\r')

  if [[ -z "$REMOTE_ETAG" ]]; then
    return 1
  fi

  # Check if a local ETag exists
  if [[ -f "$LOCAL_ETAG_FILE" ]]; then
    LOCAL_ETAG=$(cat "$LOCAL_ETAG_FILE")
    # If the ETag matches, skip the download
    if [[ "$REMOTE_ETAG" == "$LOCAL_ETAG" ]]; then
      return 0
    fi
  fi

  # Download the file as it is either outdated or does not exist
  echo "Downloading file..."
  if curl -s "$TEAM_INDEX" -o "$LOCAL_FILE"; then
    # Save the new ETag
    echo "$REMOTE_ETAG" > "$LOCAL_ETAG_FILE"
    return 0
  else
    return 1
  fi
}

function newest-chart-version() {
  LOCAL_INDEX_FILE="./build/charts-index.yaml"
  # Fetch the latest index
  fetch-team-charts-index >/dev/null

  CHART_TARGET=$1
  YQ_QUERY=".entries[\"${CHART_TARGET}\"][0].version"
  NEWEST_CHART=$(yq "$YQ_QUERY" "$LOCAL_INDEX_FILE")
  echo "$NEWEST_CHART"
}

function fetch-team-chart() {
  CHART_TARGET="${1}"
  BASE_FETCH_URL="$CHARTS_REPO/refs/heads/$CHARTS_BRANCH/assets"
  CHART_VERSION="${2}"
  FETCH_URL="${BASE_FETCH_URL}/${CHART_TARGET}/${CHART_TARGET}-${CHART_VERSION}.tgz"
  echo "Fetching version $CHART_VERSION of $CHART_TARGET"
  BUILD_DIR="./build/charts"
  mkdir -p "$BUILD_DIR"
  LOCAL_FILE="$BUILD_DIR/${CHART_TARGET}-${CHART_VERSION}.tgz"
  LOCAL_ETAG_FILE="$LOCAL_FILE.etag"

  # Ensure the build directory exists
  mkdir -p "$BUILD_DIR"

  # Fetch the ETag from the remote file headers
  REMOTE_ETAG=$(curl -sI "$FETCH_URL" | grep -i "etag" | awk '{print $2}' | tr -d '\r')

  if [[ -z "$REMOTE_ETAG" ]]; then
    return 1
  fi

  # Check if a local ETag exists
  if [[ -f "$LOCAL_ETAG_FILE" ]]; then
    LOCAL_ETAG=$(cat "$LOCAL_ETAG_FILE")
    # If the ETag matches, skip the download
    if [[ "$REMOTE_ETAG" == "$LOCAL_ETAG" ]]; then
      return 0
    fi
  fi

  # Download the file as it is either outdated or does not exist
  echo "Downloading file..."
  if curl -s "$FETCH_URL" -o "$LOCAL_FILE"; then
    # Save the new ETag
    echo "$REMOTE_ETAG" > "$LOCAL_ETAG_FILE"
    return 0
  else
    return 1
  fi
}