#!/usr/bin/env bash

function is_gnu_sed(){
  sed --version >/dev/null 2>&1
}

function sed_i_wrapper(){
  if is_gnu_sed; then
    $(which sed) "$@"
  else
    a=()
    for b in "$@"; do
      [[ $b == '-i' ]] && a=("${a[@]}" "$b" "") || a=("${a[@]}" "$b")
    done
    $(which sed) "${a[@]}"
  fi
}

function edit-chart() {
    sed_i_wrapper -i \
        -e 's/^version:.*/version: '${2}'/' \
        -e 's/^appVersion:.*/appVersion: '${3}'/' \
        "${1}"

  if [ $# -ge 4 ]; then  # Check if at least 4 arguments were passed
    sed_i_wrapper -i \
      -e "s#repository: rancher/prometheus-federator#repository: ${4}/prometheus-federator#" \
      "${1/Chart.yaml/values.yaml}"
  fi
}

function package-chart() {
    helm package --debug "${1:-"./build/charts/helm-project-operator"}" -d "${2:-"./build/charts"}"
}

function clean-old-charts() {
  if [[ -d "./build/charts/${1}" ]]; then
    rm -rf "./build/charts/${1}"
  fi
  if [[ ! -d "./build/charts" ]]; then
    mkdir -p "./build/charts"
  fi
}