#!/usr/bin/env bash
set -e

echo "Validating packages..."
cd $(dirname $0)/..

monitoring_pkg_path=packages/rancher-project-monitoring/package.yaml
monitoring_url="$(yq e '.url' ${monitoring_pkg_path})"
monitoring_subdirectory="$(yq e '.subdirectory' ${monitoring_pkg_path})"
monitoring_commit="$(yq e '.commit' ${monitoring_pkg_path})"

grafana_pkg_path=packages/rancher-project-monitoring/generated-changes/dependencies/grafana/dependency.yaml
grafana_url="$(yq e '.url' ${grafana_pkg_path})"
grafana_subdirectory="$(yq e '.subdirectory' ${grafana_pkg_path})"
grafana_commit="$(yq e '.commit' ${grafana_pkg_path})"

if [[ "${monitoring_url}" != "${grafana_url}" ]]; then
    echo "ERROR: Expected .url in ${grafana_pkg_path} (found ${grafana_url}) to match .url in ${monitoring_pkg_path} (found ${monitoring_url})"
    exit 1
fi

if [[ "${monitoring_subdirectory}/charts/grafana" != "${grafana_subdirectory}" ]]; then
    echo "ERROR: Expected .subdirectory in ${grafana_pkg_path} (found ${grafana_subdirectory}) to be charts/grafana within the .subdirectory in ${monitoring_pkg_path} (found ${monitoring_subdirectory})"
    exit 1
fi

if [[ "${monitoring_commit}" != "${grafana_commit}" ]]; then
    echo "ERROR: Expected .commit in ${grafana_pkg_path} (found ${grafana_commit}) to match .commit in ${monitoring_pkg_path} (found ${monitoring_commit})"
    exit 1
fi

echo "Completed validating packages"