#!/usr/bin/env bash
set -e

source $(dirname $0)/version
cd $(dirname $0)/..

echo "[validate-ci] starting to validate"
echo "Running go mod tidy"
go mod tidy

echo "Running go mod verify"
go mod verify

if [ -f "generate.go" ]; then
  echo "Verifying code is generated and repo is clean"
  go generate
fi

if [ -n "$DIRTY" ]; then
    echo Git is dirty
    git status
    git diff
    exit 1
fi

echo "[validate-ci] success"
