#!/bin/bash
set -e

cd $(dirname $0)/..

echo "Verifying code is generated and repo is clean"
go generate

source ./scripts/version

if [ -n "$DIRTY" ]; then
    echo Git is dirty
    git status
    git diff
    exit 1
fi
