#!/bin/bash
set -x

CHARTS_BUILD_SCRIPTS_REPO=https://github.com/rancher/charts-build-scripts.git
CHARTS_BUILD_SCRIPT_VERSION=v0.9.2

if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
    DIRTY="-dirty"
fi

COMMIT=$(git rev-parse --short HEAD)
GIT_TAG=$(git tag -l --contains HEAD | head -n 1)

if [[ -z "$DIRTY" && -n "$GIT_TAG" ]]; then
    VERSION=$GIT_TAG
else
    VERSION="${COMMIT}${DIRTY}"
fi

ARCH=$TARGET_ARCH
if [ -z "$ARCH" ]; then
    ARCH=$(go env GOHOSTARCH)
fi

SUFFIX="-${ARCH}"

TAG=${TAG:-${VERSION}}
REPO=${REPO:-rancher}

if echo "$TAG" | grep -q dirty; then
    TAG="v0.0.0-dev.1-${COMMIT}"
fi
IMAGE=${IMAGE:-"$REPO/prometheus-federator:${TAG}"}

function print_version_debug() {
    echo "BUILD_TARGET: $BUILD_TARGET";
    echo "SUFFIX: $SUFFIX";
    echo "REPO: $REPO; TAG: $TAG";
    echo "IMAGE: $IMAGE";
}
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then print_version_debug "$1"; fi