#!/usr/bin/env bash

BUILD_TARGET=${BUILD_TARGET:-"prometheus-federator"}

export KUBECONFIG=$KUBECONFIG

if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
    DIRTY="-dirty"
fi

COMMIT=$(git rev-parse --short HEAD)
GIT_TAG=${GIT_TAG:-$(git tag -l --contains HEAD | tail -n 1)}

if [[ -z "$DIRTY" && -n "$GIT_TAG" ]]; then
    VERSION=$GIT_TAG
else
    VERSION="${COMMIT}${DIRTY}"
fi

ARCH=$TARGET_ARCH
if [ -z "$ARCH" ]; then
    ARCH=$(go env GOHOSTARCH)
fi

SUFFIX="-${ARCH}"

TAG=${TAG:-${VERSION}}
REPO=${REPO:-rancher}

HELM_IMAGE_TAG=${HELM_IMAGE_TAG:-${TAG}}
if [ "$TAG" == "$COMMIT" ]; then
  HELM_CHART_VERSION="0.0.0-dev+${COMMIT}"
else
  HELM_CHART_VERSION=${HELM_IMAGE_TAG/v/}
fi

if echo "$TAG" | grep -q dirty; then
    TAG="v0.0.0-dev.1-${COMMIT}"
    HELM_IMAGE_TAG=$TAG
    HELM_CHART_VERSION=${HELM_CHART_VERSION_DEV:-${HELM_IMAGE_TAG/v/}}
fi
IMAGE=${IMAGE:-"$REPO/${BUILD_TARGET}:${TAG}"}

# Fetch build.yaml path and constant defined in it
ROOT_DIR=$(dirname "$(realpath "$(dirname "${BASH_SOURCE[0]}")")")
BUILD_YAML_PATH="$ROOT_DIR/build.yaml"
RANCHER_PROJECT_MONITORING=${RANCHER_PROJECT_MONITORING:-$(grep 'rancherProjectMonitoringVersion' "$BUILD_YAML_PATH"|cut -d: -f2|tr -d ' ')}
RANCHER_MONITORING=${RANCHER_MONITORING:-$(grep 'rancherMonitoringVersion' "$BUILD_YAML_PATH"|cut -d: -f2|tr -d ' ')}

function print_version_debug() {
    echo "DIRTY: $DIRTY"
    echo "BUILD_TARGET: $BUILD_TARGET";
    echo "SUFFIX: $SUFFIX";
    echo "HELM_IMAGE_TAG: $HELM_IMAGE_TAG";
    echo "HELM_CHART_VERSION: $HELM_CHART_VERSION";
    echo "REPO: $REPO; TAG: $TAG";
    echo "IMAGE: $IMAGE";
    echo "BUILD_YAML_PATH: $BUILD_YAML_PATH"
    echo "RANCHER PROJECT MONITORING: $RANCHER_PROJECT_MONITORING"
    echo "RANCHER MONITORING: $RANCHER_MONITORING"
}
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then print_version_debug "$1"; fi