# Image that provides cross compilation tooling.
FROM --platform=$BUILDPLATFORM rancher/mirrored-tonistiigi-xx:1.5.0 AS xx

FROM registry.suse.com/bci/golang:1.23 AS builder

# Allow chart version config
ARG TARGETPLATFORM
ARG TARGETARCH
ARG RANCHER_PROJECT_MONITORING=''
ARG TAG=''
ARG REPO=''
ARG YQ_VERSION='v4.25.1'
ENV RANCHER_PROJECT_MONITORING=$RANCHER_PROJECT_MONITORING TAG=$TAG REPO=$REPO

WORKDIR /usr/src/app
RUN zypper -n install git vim less file curl wget patch helm jq
RUN wget https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_${TARGETARCH} -O /usr/bin/yq \
    && chmod +x /usr/bin/yq
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN ./scripts/build

FROM registry.suse.com/bci/bci-micro:latest
RUN echo 'prometheus:x:1000:1000::/home/prometheus:/bin/bash' >> /etc/passwd && \
    echo 'prometheus:x:1000:' >> /etc/group && \
    mkdir /home/prometheus && \
    chown -R prometheus:prometheus /home/prometheus
COPY --from=builder /usr/src/app/build/bin/prometheus-federator /usr/bin/
USER prometheus
CMD ["prometheus-federator"]
