FROM --platform=$BUILDPLATFORM registry.suse.com/bci/golang:1.24 AS builder
WORKDIR /usr/src/app
RUN zypper -n install git vim less file curl wget
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN BUILD_TARGET=helm-locker make build

FROM registry.suse.com/bci/bci-micro:15.6
RUN echo 'helmlocker:x:1000:1000::/home/helmlocker:/bin/bash' >> /etc/passwd && \
    echo 'helmlocker:x:1000:' >> /etc/group && \
    mkdir /home/helmlocker && \
    chown -R helmlocker:helmlocker /home/helmlocker
COPY --from=builder /usr/src/app/build/bin/helm-locker /usr/bin/
USER helmlocker
CMD ["helm-locker"]
