# Image that provides cross compilation tooling.
FROM --platform=$BUILDPLATFORM rancher/mirrored-tonistiigi-xx:1.5.0 AS xx

FROM registry.suse.com/bci/golang:1.26 AS builder
ARG TARGETARCH

ENV BUILD_TARGET="helm-project-operator"

WORKDIR /usr/src/app
RUN zypper -n install git curl wget make helm
RUN export ARCH=$(go env GOHOSTARCH)

COPY ./package/install-yq.sh /tmp/install-yq.sh
RUN chmod +x /tmp/install-yq.sh && /tmp/install-yq.sh && rm /tmp/install-yq.sh


COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN make build

FROM registry.suse.com/bci/bci-micro:latest
RUN echo 'helmprojectoperator:x:1000:1000::/home/helmprojectoperator:/bin/bash' >> /etc/passwd && \
    echo 'helmprojectoperator:x:1000:' >> /etc/group && \
    mkdir /home/helmprojectoperator && \
    chown -R helmprojectoperator:helmprojectoperator /home/helmprojectoperator
COPY --from=builder /usr/src/app/build/bin/helm-project-operator /usr/bin/
USER helmprojectoperator
CMD ["helm-project-operator"]
