# Image that provides cross compilation tooling.
FROM --platform=$BUILDPLATFORM rancher/mirrored-tonistiigi-xx:1.5.0 AS xx

FROM --platform=$BUILDPLATFORM registry.suse.com/bci/golang:1.23 AS builder
ARG TARGETARCH
ENV BUILD_TARGET="helm-project-operator"
WORKDIR /usr/src/app
ENV YQ_VERSION=v4.45.2
RUN zypper -n install git curl wget make helm
RUN export ARCH=$(go env GOHOSTARCH)
RUN wget https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_${TARGETARCH} -O /usr/bin/yq && chmod +x /usr/bin/yq;
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN make build

FROM registry.suse.com/bci/bci-micro:latest
RUN echo 'helmprojectoperator:x:1000:1000::/home/helmprojectoperator:/bin/bash' >> /etc/passwd && \
    echo 'helmprojectoperator:x:1000:' >> /etc/group && \
    mkdir /home/helmprojectoperator && \
    chown -R helmprojectoperator:helmprojectoperator /home/helmprojectoperator
COPY --from=builder /usr/src/app/build/bin/helm-project-operator /usr/bin/
USER helmprojectoperator
CMD ["helm-project-operator"]
