name: "[prom-fed] ci"

on:
  workflow_call:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '.gitignore'
      - '../CODEOWNERS'
      - 'LICENSE'
      - 'Makefile'
  push:
    branches:
      - main
      - release/v[0-9]+.x
      - release/v[0-9]+.[0-9]+.[0-9]+
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '.gitignore'
      - '../CODEOWNERS'
      - 'LICENSE'

jobs:
  build:
    uses: rancher/prometheus-federator/.github/workflows/ci.yaml@35be137f458fb12ba55466e58a60ecbbe94fa2a7 # automation-core
    with:
      helm-version: 'v4.2.0'
