name: "[prom-fed] ci"

on:
  workflow_call:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - 'Makefile'
  push:
    branches:
      - main
      - release/v[0-9]+.x
      - release/v[0-9]+.[0-9]+.[0-9]+
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'

env:
  CGO_ENABLED : 0

jobs:
  build:
    strategy:
      matrix:
        arch:
          - x64
          - arm64
    runs-on: ${{ github.repository == 'rancher/prometheus-federator' && format('runs-on,image=ubuntu22-full-{1},runner=4cpu-linux-{1},run-id={0}', github.run_id, matrix.arch) || 'ubuntu-latest' }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name : Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: '1.26'
      - name: Check if yq is installed
        id: check_yq
        run: |
          if ! command -v yq &> /dev/null; then
            echo "yq not found, installing..."
            echo "::set-output name=install_yq::true"
          else
            echo "yq is already installed"
            echo "::set-output name=install_yq::false"
          fi
      - name : Install YQ
        if: steps.check_yq.outputs.install_yq == 'true'
        run: |
          ./package/install-yq.sh
      - name : Install helm
        uses: azure/setup-helm@dda3372f752e03dde6b3237bc9431cdc2f7a02a2 # v5.0.0
        with:
          version: 'v3.19.5'
      - name: Run CI
        run: make ci
