name : Integration test

permissions:
  contents : read

on:
  workflow_call:
  push:
    branches:
      - main
      - release/v[0-9]+.(0|x)
      - release/v[0-9]+.[0-9]+.[0-9]+
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '.gitignore'
      - '../CODEOWNERS'
      - 'LICENSE'
  pull_request:
    paths-ignore:
    - 'docs/**'
    - '*.md'
    - '.gitignore'
    - '../CODEOWNERS'
    - 'LICENSE'

jobs:
  test:
    uses: rancher/prometheus-federator/.github/workflows/integration.yaml@automation-core
    with:
      helm-version: 'v4.2.0'
      k3s-versions: '["v1.34.7-k3s1","v1.36.0-k3s1"]'
