name: golangci-lint

on:
  pull_request:
    paths-ignore:
    - 'docs/**'
    - '*.md'
    - '.gitignore'
    - '../CODEOWNERS'
    - 'LICENSE'

permissions:
  contents: read

jobs:
  golangci:
    uses: rancher/prometheus-federator/.github/workflows/lint.yaml@35be137f458fb12ba55466e58a60ecbbe94fa2a7 # automation-core
    with:
      helm-version: 'v4.2.0'
