name: Produce PR dev images (on Request)

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull Request Number to build image for'
        required: true
        type: number

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write
  pull-requests: write

jobs:
  produce-pr-images:
    uses: rancher/prometheus-federator/.github/workflows/pr-debug-publish.yaml@35be137f458fb12ba55466e58a60ecbbe94fa2a7 # automation-core
    with:
      pr_number: ${{ inputs.pr_number }}
