name : Publish images, charts and binaries

on:
  push:
    tags:
      - "v*"

env:
  GHCR_REGISTRY: ghcr.io
  PUBLIC_REGISTRY: docker.io
  REPO: rancher
  IMAGE_NAME: 'prometheus-federator'

jobs:
  ci:
    uses: ./.github/workflows/ci.yaml
  integration:
    uses: ./.github/workflows/integration.yaml
  e2e:
    uses : ./.github/workflows/prom-fed-e2e-ci.yaml
  goreleaser:
    name: Build go binaries and helm chart
    runs-on: ${{ github.repository == 'rancher/prometheus-federator' && format('runs-on,image=ubuntu22-full-x64,runner=4cpu-linux-x64,run-id={0}', github.run_id) || 'ubuntu-latest' }}
    needs: [
      ci,
      integration,
    ]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GORELEASER_CURRENT_TAG: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - name : setup Go
        uses : actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5
        with:
          go-version: 1.26
      - name: Check if yq is installed
        id: check_yq
        run: |
          if ! command -v yq &> /dev/null; then
            echo "yq not found, installing..."
            echo "::set-output name=install_yq::true"
          else
            echo "yq is already installed"
            echo "::set-output name=install_yq::false"
          fi
      - name : Install YQ
        if: steps.check_yq.outputs.install_yq == 'true'
        run: |
          ./package/install-yq.sh
      - uses: azure/setup-kubectl@829323503d1be3d00ca8346e5391ca0b07a9ab0d # v5.1.0
      - name : Install helm
        uses: azure/setup-helm@dda3372f752e03dde6b3237bc9431cdc2f7a02a2 # v5.0.0
        with:
          version: 'v3.19.5'
      - name: Prepare helm charts (needed for build)
        run: |
          GIT_TAG=${{ github.ref_name }} BUILD_TARGET=prometheus-federator make package-helm && echo "pf: release chart prepared"
          BUILD_TARGET=prometheus-federator make build-chart && echo "pf: embedded project-monitoring chart prepared"
      - uses: goreleaser/goreleaser-action@1a80836c5c9d9e5755a25cb59ec6f45a3b5f41a8 # v7.2.1
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_CURRENT_TAG: ${{ github.ref_name }}
  push-dev-images:
    name : Build and push helm-locker & Helm-Project-Operator images
    runs-on: ${{ github.repository == 'rancher/prometheus-federator' && format('runs-on,image=ubuntu22-full-x64,runner=4cpu-linux-x64,run-id={0}', github.run_id) || 'ubuntu-latest' }}
    needs: [
      ci,
      integration,
    ]
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name : Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0
      - name: Log in to the Container registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Helm-Project-Operator image
        id: meta-hpo
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
        with:
          images: ${{ env.GHCR_REGISTRY }}/${{ env.REPO }}/${{ env.IMAGE_NAME }}/helm-project-operator
      - name: Build Helm-Project-Operator image
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
        with:
          context: .
          file: ./package/Dockerfile-helm-project-operator
          push: true
          tags: ${{ steps.meta-hpo.outputs.tags }}
          labels: ${{ steps.meta-hpo.outputs.labels }}
          platforms: linux/amd64,linux/arm64

  publish-images:
    name: Publish prometheus-federator image
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: [
      ci,
      integration,
      e2e,
    ]
    permissions:
      contents : read
      id-token: write
    steps:
      - name : Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Prepare helm charts (needed for build)
        run: |
          GIT_TAG=${{ github.ref_name }} BUILD_TARGET=prometheus-federator make package-helm && echo "pf: release chart prepared"
          BUILD_TARGET=prometheus-federator make build-chart && echo "pf: embedded project-monitoring chart prepared"
      - name: "Read public and prime stg secrets"
        if: github.repository == 'rancher/prometheus-federator'
        uses: rancher-eio/read-vault-secrets@0da85151ad1f19ed7986c41587e45aac1ace74b6 # v3
        with:
          secrets: |
            secret/data/github/repo/${{ github.repository }}/rancher-prime-stg-registry/credentials registry |  PRIME_STG_REGISTRY;
            secret/data/github/repo/${{ github.repository }}/rancher-prime-stg-registry/credentials username |  PRIME_STG_REGISTRY_USERNAME;
            secret/data/github/repo/${{ github.repository }}/rancher-prime-stg-registry/credentials password |  PRIME_STG_REGISTRY_PASSWORD;
            secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials username | DOCKER_USERNAME ;
            secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials password | DOCKER_PASSWORD
      - name: Build and push prometheus-federator image (dockerhub and prime stg)
        uses: rancher/ecm-distro-tools/actions/publish-image@a7a867a6376bf4a1cee397558f3c85393769f069 # v0.69.4
        with:
          image: ${{ env.IMAGE_NAME }}
          tag: ${{ github.ref_name }}
          identity-registry: ${{ env.PRIME_STG_REGISTRY }}
          public-registry: ${{ env.PUBLIC_REGISTRY }}
          public-repo: ${{ env.REPO }}
          public-username: ${{ env.DOCKER_USERNAME || vars.DOCKER_USERNAME || github.repository_owner }}
          public-password: ${{ env.DOCKER_PASSWORD || secrets.DOCKER_PASSWORD }}

          push-to-prime: ${{ github.repository == 'rancher/prometheus-federator' }}
          prime-registry: ${{ env.PRIME_STG_REGISTRY }}
          prime-repo: ${{ env.REPO }}
          prime-username: ${{ env.PRIME_STG_REGISTRY_USERNAME }}
          prime-password: ${{ env.PRIME_STG_REGISTRY_PASSWORD }}
      - name: Check SemVer Characteristics
        id: semver_check
        run: bash ./.github/scripts/check-semver "${{ github.ref_name }}" >> "$GITHUB_OUTPUT"
      - name: "Read prime prod secrets"
        if: ${{github.repository == 'rancher/prometheus-federator' && steps.semver_check.outputs.HAS_PRERELEASE == 'false'}}
        uses: rancher-eio/read-vault-secrets@0da85151ad1f19ed7986c41587e45aac1ace74b6 # v3
        with:
          secrets: |
            secret/data/github/repo/${{ github.repository }}/rancher-prime-registry/credentials registry |  PRIME_REGISTRY;
            secret/data/github/repo/${{ github.repository }}/rancher-prime-registry/credentials username |  PRIME_REGISTRY_USERNAME;
            secret/data/github/repo/${{ github.repository }}/rancher-prime-registry/credentials password |  PRIME_REGISTRY_PASSWORD;
      - name: Build and push prometheus-federator image (prod)
        if: ${{github.repository == 'rancher/prometheus-federator' && steps.semver_check.outputs.HAS_PRERELEASE == 'false'}}
        uses: rancher/ecm-distro-tools/actions/publish-image@a7a867a6376bf4a1cee397558f3c85393769f069 # v0.69.4
        with:
          image: ${{ env.IMAGE_NAME }}
          tag: ${{ github.ref_name }}
          push-to-public: false
          push-to-prime: true
          prime-registry: ${{ env.PRIME_REGISTRY }}
          prime-repo: rancher
          prime-username: ${{ env.PRIME_REGISTRY_USERNAME }}
          prime-password: ${{ env.PRIME_REGISTRY_PASSWORD }}
