workingDir: ""
url: https://github.com/rancher/charts.git
subdirectory: charts/rancher-monitoring/102.0.0+up40.1.2
commit: 970470cf8b779b926e8ced60a10f270e401a44a4
version: 0.2.2
ignoreDependencies:
  - hardenedKubelet
  - hardenedNodeExporter
  - k3sServer
  - kube-state-metrics
  - kubeAdmControllerManager
  - kubeAdmProxy
  - kubeAdmScheduler
  - kubeAdmEtcd
  - prometheus-adapter
  - prometheus-node-exporter
  - rke2ControllerManager
  - rke2Etcd
  - rke2IngressNginx
  - rke2Proxy
  - rke2Scheduler
  - rkeControllerManager
  - rkeEtcd
  - rkeIngressNginx
  - rkeProxy
  - rkeScheduler
  - windowsExporter
replacePaths:
  - README.md
  - app-README.md
