workingDir: ""
url: https://github.com/rancher/charts.git
subdirectory: charts/rancher-monitoring/101.1.0+up40.1.2
commit: 474720e374b13e27ae35566d6f4b7714a37d5814
version: 0.2.0-rc4
ignoreDependencies:
  - hardenedKubelet
  - hardenedNodeExporter
  - k3sServer
  - kube-state-metrics
  - kubeAdmControllerManager
  - kubeAdmProxy
  - kubeAdmScheduler
  - kubeAdmEtcd
  - prometheus-adapter
  - prometheus-node-exporter
  - rke2ControllerManager
  - rke2Etcd
  - rke2IngressNginx
  - rke2Proxy
  - rke2Scheduler
  - rkeControllerManager
  - rkeEtcd
  - rkeIngressNginx
  - rkeProxy
  - rkeScheduler
  - windowsExporter
replacePaths:
  - README.md
  - app-README.md
